# Test generated by RoostGPT for test roostPostmanTest using AI Type Azure Open AI and AI Model roost-gpt4-32k

# RoostTestHash=2c3a7f4837

config:
  target: "{{ $processEnvironment.API_HOST }}"
  plugins:
    expect: {}
  payload:
    path: "pet_petId_get_others.csv"
    fields:
      - "petId"
    skipHeader: true
  phases:
    - duration: 60
      arrivalRate: 20

scenarios:
  - name: "API Tests"
    flow:
      - think: 2
        log: "Attempting API with invalid ID"
        get:
          url: "/pet/invalidID"
          headers: 
            Authorization: "{{ $processEnvironment.AUTH_TOKEN }}"
            Content-Type: "application/x-www-form-urlencoded"
          expect: 
            - statusCode: 400
            - hasProperty: "message"
            - hasProperty: "error"

      - think: 2
        log: "Attempting API with petId not found in store"
        get:
          url: "/pet/{{ petId }}"
          headers: 
            Authorization: "{{ $processEnvironment.AUTH_TOKEN }}"
            Content-Type: "application/x-www-form-urlencoded"
          expect: 
            - statusCode: 404
            - hasProperty: "message"
            - hasProperty: "error"

      - think: 2
        log: "Attempting API with incorrect authorization header"
        get:
          url: "/pet/{{ petId }}"
          headers: 
            Authorization: "Bearer randomToken"
            Content-Type: "application/x-www-form-urlencoded"
          expect: 
            - statusCode: 401
            - hasProperty: "message"
            - hasProperty: "error"
            
      - think: 2
        log: "Attempting API with incorrect url"
        get:
          url: "/pets/{{ petId }}"
          headers: 
            Authorization: "{{ $processEnvironment.AUTH_TOKEN }}"
            Content-Type: "application/x-www-form-urlencoded"
          expect: 
            - statusCode: 404
            - hasProperty: "message"
            - hasProperty: "error"
